version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/cycle-project
        environment:
            - $env:FLASK_APP = "server.py"